name: Maven Build Scan
on: workflow_dispatch
jobs:
  build-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -X -U